version: '3'
services:
  todoapp:
    container_name: todoapp
    image: todoapp
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: mongodb://mongodb:27017/todoapp
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
